import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:frontend/models/employee.dart';
import 'package:frontend/models/vacation_entry.dart';
import 'package:hive/hive.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'employee_request.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'employee_request.g.dart';

@freezed
class EmployeeRequest with _$EmployeeRequest {
  @HiveType(typeId: 10, adapterName: 'EmployeeRequestAdapter')
  const factory EmployeeRequest({
    @JsonKey(name: "id") @HiveField(0) required String id,
    @JsonKey(name: "employeeId") @HiveField(1) required String employeeId,
    @JsonKey(name: "vacation_entry") @HiveField(2) required VacationEntry vacationEntry,
  }) = _EmployeeRequest;

  factory EmployeeRequest.fromJson(Map<String, Object?> json) =>
      _$EmployeeRequestFromJson(json);
}