import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:hive/hive.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'product.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'product.g.dart';

@freezed
class Product with _$Product {
  @HiveType(typeId: 1, adapterName: 'ProductAdapter')
  const factory Product({
    @JsonKey(name: "id") @HiveField(0) required String id,
    @JsonKey(name: "name") @HiveField(1) required String name,
  }) = _Product;

  factory Product.fromJson(Map<String, Object?> json) => _$ProductFromJson(json);
}
