version: "3"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args: #WARNING: args not working, needs to be manually configured in appsettings.json
        MARIADB_DATABASE: "${DB_NAME}"
        MARIADB_USER: "${DB_USER}"
        MARIADB_PASSWORD: "${DB_PASSWORD}"
    restart: 'unless-stopped'
    ports:
      - "${API_PORT}:80"
      - "3002:5224"
    depends_on:
      - database
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: 'unless-stopped'
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "./database/container:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
