version: "3"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: 'unless-stopped'
    ports:
      - "${API_PORT}:80"
    depends_on:
      - mariadb
    environment:
      MARIADB_HOST: "mariadb"
      MARIADB_DATABASE: "clock_in"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      
  mariadb:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: 'unless-stopped'
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "./database/container:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "clock_in"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"